{{*
 *	AUTOMATICALLY GENERATED TEMPLATE
 *	DO NOT EDIT THIS FILE, CHANGES WILL BE OVERWRITTEN
 *
 *}}
{{include file="field_input.tpl" field=$method1}}
{{include file="field_input.tpl" field=$method_1_link}}
{{include file="field_input.tpl" field=$method2}}
{{include file="field_input.tpl" field=$method_2_link}}
{{include file="field_input.tpl" field=$method3}}
{{include file="field_input.tpl" field=$method_3_link}}
{{include file="field_input.tpl" field=$method4}}
{{include file="field_input.tpl" field=$method_4_link}}
{{include file="field_input.tpl" field=$method5}}
{{include file="field_input.tpl" field=$method_5_link}}
<div class="submit"><input type="submit" name="page_site" value="{{$submit}}" /></div>

